# The caching manager configuration
# This option controls the default session "driver" that will be used on requests.
# By default, we will use the lightweight native driver but
# you may specify any of the other wonderful drivers provided here.
caching:
    # Supported: "filesystem", "redis", "sqlite", "memcache", "apcu"
    # "xcache", 'memory' "zenddata", "wincache", and memcached
    driver: filesystem

    # The supported connections into caching.
    # Here are each of the connections setup for your application. Examples of
    # configuring each supported driver is shown below.
    pools:
        # Here you can set in the file location into the option connection.
        # By default the path is set to `storage/caches`.
        filesystem: { connection: ~, extension: .temp }

        # Here you can set in the file location into the option connection.
        # By default the path is set to `storage/caches`.
        memory: { connection: ~, extension: .php }

        # Here is the connection options for the Redis php extension
        redis:
            connection: localhost:6379

        # Here is the connection options for the Memcache php extension
        # This driver is somehow deprecated, but works. Use with caution !!!
        memcache:
            connection: localhost:11211

        # Here is the connection options for the Memcached php extension
        memcached:
            connection: localhost:11211

        # Here is the connection options for the SQLITE php extension
        # By default the path is set to `storage/database/caching.db`.
        sqlite: { connection: caching.db, table: caching }
