# The Framework Loading system
loader:
    # Load All Classes and Files found in directories
    locators:
        # The paths to look into and fetch files, directory and classes
        paths: ["%path.APP%"]
        # The excluded paths, locator should not access
        excludes: ~

    # Load a set of configurations to be accessed globally in application.
    data_path: "%path.ROOT%/config/global-config.php"

    # This options is used to load all paths found in the
    # directory where composer is installed.
    # Optionally, you can set it to composer's vendor directory or use
    # "%path.VENDOR%/composer.installed.json" file.
    composer_path: ~

    # This is a powerful feature of biurad-loader allows to register a new
    # resource path that will be used in codebase and
    # accessed from "ResourceLocatorInterface", findResource methods.
    resources:
        app: app
        config: config
        routes: routing
        vendor: vendor
        public: public
        views: resources
        storage: storage
        logs: storage://logs
        caches: storage://caches
        uploads: storage://uploads

    # This array of classes or namespaces aliases will be registered before application
    # is started. However, feel free to register as many as you wish as
    # the aliases are "lazy" loaded so they don't hinder performance.
    aliases:
        # Put annotations on class alias, in case developer omits by mistake.
        Router: BiuradPHP\Routing\Annotation\Route
        Event: BiuradPHP\Events\Annotation\Listener

        # Handled by Framework...
        App: BiuradPHP\MVC\Application
        Facade: BiuradPHP\MVC\Framework
