# Set configs in php.ini.
# This is assigned to php builtin function "ini_set".
php:
    # Set the default date timezone for your app
    date.timezone: Africa/Accra

    # Maximum memory allocated to store the results
    realpath_cache_size: 4096K

    # Save the results for 10 minutes (600 seconds)
    realpath_cache_ttl: 600
