# Register your scaffold's here. Scaffold's help ease development
scaffolder:
    root_directory: '%path.APP%' # Default directory where generated scaffold will be placed
    view_directory: '%path.APP%/mvc/views' # Default directory where generated templates will be placed

    namespace: ~ # Leave as it is to avoid conflict in generating scaffold's.

    # This header will be added to all generated scaffold's.
    header:
        - '{project-identity}' # Change it to your project name, title or notice
        - '' # Adding an empty string return's it as spaces, meaning "\n".
        - PHP version 7 and above required
        - '' # Adding an empty string return's it as spaces, meaning "\n".
        - '@author      {author-contact}' # Change it to your name and email
        - '@copyright   {copyright-description}' # Change it to your copyright description
        - '@license     {license-description}' # Change it to the project license type

    # This section contains all declarations needed for generating scaffold.
    declarations:
        # The "command" name gives access for creating your terminal console scaffold command class.
        command:
            namespace: Commands # The namespace attached to "App", so it becomes "App\Commands\"
            postfix: Command # The prefix for generated scaffold, if class is "Deploy", it becomes "DeployCommand"
            class: BiuradPHP\Scaffold\Declarations\MakeCommand # The declaration been used to generate command scaffold
