# The session manager configuration
# The settings for managing php sessions.
session:
    # Supported: "cookie", "array", "cache-based", mssql://, mysql://, database or cycle,
    # pgsql://, postgres://, postgresql://, sqlsrv://, sqlite://, sqlite3://, filesystem
    driver: cache-based

    # Sets session.* ini variables.
    # For convenience we omit 'session.' from the beginning of the keys.
    # Explicitly ignores other ini keys.
    options:
        use_cookies: '1'
        cookie_secure: auto
        cookie_samesite: lax

    pools:
        # Here you may change the name of the cookie used to identify a session
        # instance by ID. The name specified here will get used every time a
        # new session cookie is created by the framework
        name: BF_SESSID

        # Here you may specify the number of minutes that you wish the session
        # to be allowed to remain idle before it expires. If you want them
        # to immediately expire on the browser closing.
        maxlifetime: 2 hours

        # The session cookie path determines the path for which the cookie will
        # be regarded as available. Typically, this will be the root path of
        # your application but you are free to change this when necessary.
        path: /

        # Here you may change the domain of the cookie used to identify a session
        # in your application. This will determine which domains the cookie is
        # available to in your application. A sensible default has been set
        domain: '%env.URL%'

        # By setting this option to true, session cookies will only be sent back
        #to the server if the browser has a HTTPS connection. This will keep
        #the cookie from being sent to you if it can not be done securely.
        secure: false

        # Setting this value to true will prevent JavaScript from accessing the
        # value of the cookie and the cookie will only be accessible through
        # the HTTP protocol. You are free to modify this option if needed.
        httponly: true
