# The template manager configuration
# Most templating systems load templates from disk. Here you may specify
# an array of paths that should be checked for your views. Of course
# the usual view paths has already been registered for you.
templating:
    # Add paths where template files will be placed.
    path: ["%path.ROOT%/resources"]

    # The path templates cached, will be retrieved from.
    cache_path: "%path.TEMP%/caches/biurad.views"

    # Add the driver to the view. e.g BiuradPHP\Template\Engines\PhtmlEngine
    drivers: ~

    # This helps in accessing template views when files have same names and placed in
    # different directories. access file by: e.g. @Base::welcome or #Base::welcome
    namespaces:
        Base: "%path.ROOT%/resources"
