# Put parameters here that don't need to change on each machine where the app is deployed
# Parameters defined are called using "%" around it in any config you create.
parameters:
    # default configuration for framework to work in *this* file
    env:
        # This parameter defines the codes of the locales (languages) enabled in the application
        LOCALES: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt

        # The 'ide' option turns all of the file paths in an pages where needed as default homepage path
        # into clickable links that open the given file using your favorite IDE.
        # When 'ide' is set to null the file is opened in your web browser.
        # Works only in development mode.
        IDE: 'editor://%action/?file=%file&line=%line&search=%search&replace=%replace'

        # This salt and CIPHER should not be touched unless you know what you're doing
        # SECRET: {enter key generated in env file APP_KEY section or leave it as it is}
        SALT: '8qk9c^4L6d;15tM8z7n0%'
        CIPHER: '%env(SECURITY_CIPHER|AES-256-CBC)%'
        SECRET: '%env(APP_KEY)%'

    # Used to restrict access for large sections of your site
    # Note: This works mostly on routing, and can work on all routes if specified
    # If you are using a different security system, allow you code to use this parameters.
    access:
        # This adds a Content-Security-Policy to response headers sent to browser.
        # For a better understanding of CSP, see these documents:
	    # - http://www.html5rocks.com/en/tutorials/security/content-security-policy/
	    # - http://www.w3.org/TR/CSP/
        CONTENT_SECURITY_POLICY: false

        # This is the master switch to enable demo mode on application.
        DEMO_MODE:
            enable: '%env(SECURITY_DEMO_MODE|false)%'
            paths: ^/test
            redirect_unauthorized: /demo-mode # Visitors browsing on matched demo paths will be redirected to this path.

            # IP's will automatically gain access to the app without restrictions.
            # specify ips example: ['23.75.345.200', '192.168.101'], in the empty array.
            authorized_ips: []

# Include our configuration ================
includes:
    - extensions.ini
    - services.yaml
